server {
    listen 80;
    server_name _;
    client_max_body_size 5M;

    location /static/ {
        alias /home/copa_cirrose_bt/staticfiles/;
        expires 7d;
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/copa_cirrose_bt/copa.sock;
    }
}
