server {
    listen 80;
    server_name _;
    client_max_body_size 5M;

    location = /copa_cirrose_bt {
        return 301 /copa_cirrose_bt/;
    }

    location /copa_cirrose_bt/static/ {
        alias /home/copa_cirrose_bt/staticfiles/;
        expires 7d;
    }

    location /copa_cirrose_bt/ {
        include proxy_params;
        proxy_pass http://unix:/home/copa_cirrose_bt/copa.sock;
    }

    location / {
        return 404;
    }
}
