# Generated by Django 5.2.13 on 2026-04-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Copa Cirrose BT', max_length=100)),
                ('status', models.CharField(choices=[('setup', 'Em Setup'), ('andamento', 'Em Andamento')], default='setup', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('sf1', 'Semifinal 1'), ('sf2', 'Semifinal 2'), ('final', 'Final')], default='grupos', max_length=10)),
                ('sets_a', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sets_b', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dupla_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_a', to='torneio.dupla')),
                ('dupla_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jogos_como_b', to='torneio.dupla')),
                ('torneio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='torneio.torneio')),
            ],
            options={
                'ordering': ['fase', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='dupla',
            name='torneio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplas', to='torneio.torneio'),
        ),
    ]
